import requests
import random
import shutil
import ctypes

path = r'C:\Users\ak19o\wallpaper.py\img.jpg'
api_url = "https://www.bing.com/HPImageArchive.aspx?format=js&n=8&mkt=en-US"

# getting the adress of the image/wallpaper  using the bing api
response = requests.get(api_url).json()

""" generating the url from the adress generated by the api call,
    randint used because the api call returns 8 images,
    the api call can be modified to return only one image """

image_url = "https://bing.com"
image_url += str(response["images"][random.randint(0, 7)]["url"])

# getting the image from the url
r = requests.get(image_url, stream=True)

# saving the image
if r.status_code == 200:
    with open(path, 'wb') as f:
        r.raw.decode_content = True
        shutil.copyfileobj(r.raw, f)

"""setting the downloaded image as a wallpaper
   might differ for different operating systems,
   the given code below works on windows 10"""
ctypes.windll.user32.SystemParametersInfoW(20, 0, path, 0)
